- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers, well-defined and small scope"
- name: "type/bug"
  color: "d73a4a"
  description: "Something is broken and needs fixing"
- name: "type/feature"
  color: "0e8a16"
  description: "New capability or enhancement request"
- name: "type/chore"
  color: "5319e7"
  description: "Maintenance work without direct feature impact"

- name: "area/core"
  color: "1d76db"
  description: "Core library and runtime behavior"
- name: "area/sdk"
  color: "0052cc"
  description: "SDK interfaces and developer ergonomics"
- name: "area/docs"
  color: "0075ca"
  description: "Documentation and guides"
- name: "area/examples"
  color: "006b75"
  description: "Sample apps and runnable examples"
- name: "area/ci"
  color: "3f51b5"
  description: "CI/CD and developer workflows"
- name: "area/security"
  color: "b60205"
  description: "Security-specific behavior and hardening"

- name: "priority/low"
  color: "c2e0c6"
  description: "Nice to have, limited urgency"
- name: "priority/medium"
  color: "fbca04"
  description: "Important and should be planned soon"
- name: "priority/high"
  color: "d93f0b"
  description: "High urgency or high impact"

- name: "status/needs-triage"
  color: "ededed"
  description: "Needs first review and labeling"
- name: "status/in-progress"
  color: "0e8a16"
  description: "Actively being worked on"
- name: "status/blocked"
  color: "b60205"
  description: "Blocked by dependency or decision"
- name: "status/stale"
  color: "f9d0c4"
  description: "No activity for a while"
